### ISSUE TITLE
Getting Error while compiling library

### ISSUE THREAD

**Issue by chnouman** [thunder413/DateTimeUtils#2]
Error:A problem occurred configuring project ':app'.
> Could not resolve all dependencies for configuration ':app:_debugApkCopy'.
   > Could not find com.github.thunder413:DateTimeUtils:1.3.
     Required by:
         project :app

**Comment by thunder413** [comment]
Sorry it was a mistake it's 
compile 'com.github.thunder413:DateTimeUtils:1.0' instead of 1.3

**Comment by chnouman** [comment]
thanks for the help great work

**Comment by thunder413** [comment]
You're welcome !! thanks :)
