### ISSUE TITLE
Changing timezone india

### ISSUE THREAD

**Issue by cybertronjc** [thunder413/DateTimeUtils#5]
Hey,
Thanks for this beautiful library. 
I am not able to change the timezone to IST(Indian standard time) as the library has a default timezone UTC. I have added a line of code that you mentioned in the about section in my launcher activity.
DateTimeUtils.setTimeZone("IST");

**Comment by shahidcodes** [comment]
try using "Asia/Kolkata"

**Comment by thunder413** [comment]
Above suggestion work i'm closing this issue thanks for the support
