### ISSUE TITLE
How to get the previous week or month date using the given date ?

### ISSUE THREAD

**Issue by ArunVicky001** [thunder413/DateTimeUtils#6]
Hi 

Thanks you very much for this library, 

Is this library supports to get the get the previous week or month date using the given date? 

Eg: 1. Given date 2019-04-03 previous week date 2019-04-26
      2. Given date 2019-04-29 previous 12 month date 2019-04-30

**Comment by thunder413** [comment]
Hello, Thanks for support
No it does not but it will be a great idea to add those features i'll be updating ASAP

**Comment by ArunVicky001** [comment]
Sounds Good!, Thank you.

**Comment by thunder413** [comment]
Hi !
I've add request features report any encountered bug
thanks for the support :)
